name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        go-version: [1.12.9, 1.13]

        
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v ./... --timeout 60s
