name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        go-version: [1.13.11, 1.14.3]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... --timeout 60s

    - name: Cross test for i386
      run: env GOOS=linux GOARCH=386 go test -v ./... --timeout 60s

    - name: Cross compile for arm (RPI)
      run: env GOOS=linux GOARCH=arm GOARM=5 go build -v ./...
